### ISSUE TITLE
AUDIOQUALITY=10 does not work

### ISSUE THREAD

**Issue by candrapersada** [Sprinter05/ytdlp-handler#1]
why does `AUDIOQUALITY=10` not work when downloading videos on windows?
and how to use `"%(uploader)s/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s"` in youtube playlist?

**Comment by Sprinter05** [comment]
`AUDIOQUALITY` is only accessed when using Audio filetypes because it uses the `-x` flag to pass the m4a to another format through ffmpeg whereas video formats use yt-dlp's merge format which already uses the best possible m4a format and does not require the `-x` flag to render.

For your second question, first of all %% is needed in Windows because batch already uses % for calling variables, therefore you must use %% and if you followed the correct format it should work.

Hope that solved your issues and sorry for the delay!

**Comment by candrapersada** [comment]
> `AUDIOQUALITY` is only accessed when using Audio filetypes because it uses the `-x` flag to pass the m4a to another format through ffmpeg whereas video formats use yt-dlp's merge format which already uses the best possible m4a format and does not require the `-x` flag to render.
> 
what I mean is how to use to select the audio quality in video
![gambar](https://user-images.githubusercontent.com/36833664/203303303-c715491c-41f7-496b-96ec-557c4d5a3740.png)
![gambar](https://user-images.githubusercontent.com/36833664/203303392-e7155dac-350d-4f73-a971-95009ada32ee.png)

> For your second question, first of all %% is needed in Windows because batch already uses % for calling variables, therefore you must use %% and if you followed the correct format it should work.

and add Full name of the playlist uploader Name of the playlist that contains the video and track number in `settings.ini`

**Comment by Sprinter05** [comment]
`AUDIQUALITY` is a parameter of the `-x` flag for converting the m4a audio to the desired quality in the output format. That is a specific option of `yt-dlp` to choose the audio stream from Youtube itself which is not implemented in this handler (at least not yet), it automatically grabs the best one from the website.

For custom output format I just remembered it's not added because of how batch handles strings in Windows, maybe one day I'll try to get it working but for now it will remain like that.
